[general]
prefix = "<gradient:#2F80ED:#FFCAC9>HackedServer <#282B3F>| "

[logs]
loaded = "<prefix><#55ffa4>Successfully enabled"
debug_message = "<#93291E>HS-Debug <#282B3F>| <#facc43><player> <#b8bbc2>channel<#6f737d>: \"<#facc43><channel><#6f737d>\", <#b8bbc2>message<#6f737d>: \"<#facc43><message><#6f737d>\""

[commands]
help = """
<prefix><#b8bbc2>Available commands
<hover:show_text:\"<gray>fill reload command\"><click:SUGGEST_COMMAND:/hackedserver reload ><#6f737d>/hs \
<#b8bbc2>reload</click></hover>  <#6f737d>»<#b8bbc2> reload the plugin<reset>
<hover:show_text:\"<gray>fill give command\"><click:SUGGEST_COMMAND:/hackedserver check ><#6f737d>/hs \
<#b8bbc2>check <#43c9fa>target</click></hover>  <#6f737d>»<#b8bbc2> check player detected mods<reset>
<hover:show_text:\"<gray>fill list command\"><click:SUGGEST_COMMAND:/hackedserver list ><#6f737d>/hs \
<#b8bbc2>list</click></hover>  <#6f737d>»<#b8bbc2> list all spotted players<reset>
"""

help_spigot = """
<prefix><#b8bbc2>Available commands
<hover:show_text:\"<gray>fill reload command\"><click:SUGGEST_COMMAND:/hackedserver reload ><#6f737d>/hs \
<#b8bbc2>reload</click></hover>  <#6f737d>»<#b8bbc2> reload the plugin<reset>
<hover:show_text:\"<gray>fill give command\"><click:SUGGEST_COMMAND:/hackedserver check ><#6f737d>/hs \
<#b8bbc2>check <#43c9fa>target</click></hover>  <#6f737d>»<#b8bbc2> check player detected mods<reset>
<hover:show_text:\"<gray>fill list command\"><click:SUGGEST_COMMAND:/hackedserver list ><#6f737d>/hs \
<#b8bbc2>list</click></hover>  <#6f737d>»<#b8bbc2> list all spotted players<reset>
"""

reload_success = "<prefix><#55ffa4>Successfully reloaded"
check_no_mods = "<prefix><#55ffa4> No mods detected"
check_mods = "<prefix><#55ffa4> Detected mods:"
mod_list_format = "<#6f737d>- <#facc43><mod>"
check_lunar_mods = "<prefix><#55ffa4> Lunar Client mods:"
check_lunar_no_mods = "<prefix><#55ffa4> No Lunar Client mods detected"
lunar_mod_list_format = "<#6f737d>- <#facc43><mod>"
check_players = "<prefix><#55ffa4> Spotted players:"
check_players_empty = "<prefix><#55ffa4> No chocolate players spotted"
player_list_format = "<#6f737d>- <#facc43><player>"
